import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:socket_io_client/socket_io_client.dart' as socket_io;
import 'package:easy_localization/easy_localization.dart';
import 'web_api_service.dart';
import 'web_appointments.dart';
import 'web_notifications.dart';
import 'web_role_model.dart';

class WebReception extends StatefulWidget {
  final UserRole userRole;
  final String staffId;

  const WebReception({super.key, required this.userRole, required this.staffId});

  @override
  State<WebReception> createState() => _WebReceptionState();
}

class _WebReceptionState extends State<WebReception> {
  // Reception has a single front desk (no office selector like Queue
  // Management), so check-ins are recorded against this office.
  static const String _receptionOffice = 'Divisional Secretariat - Colombo';

  bool isScanning = false;
  String scannedData = '';
  // Tracks the semantic outcome of the last scan so the result text's color
  // doesn't depend on matching substrings inside the (now-translatable)
  // scannedData message.
  String _scanResultKind = '';
  int activeQueueCount = 0;
  int todayArrivals = 0;
  int walkInCount = 0;

  final ScrollController _scrollController = ScrollController();
  final GlobalKey _appointmentsKey = GlobalKey();
  final GlobalKey _walkInKey = GlobalKey();

  void _scrollToSection(GlobalKey key) {
    final ctx = key.currentContext;
    if (ctx != null) {
      Scrollable.ensureVisible(ctx, duration: const Duration(milliseconds: 400), curve: Curves.easeInOut);
    }
  }

  List<Map<String, dynamic>> todayAppointments = [
    {'token': 'A-024', 'citizen': 'K.N.T. Nikethani', 'nic': '200486403960', 'service': 'Passport Renewal', 'time': '10:30 AM', 'status': 'Checked In', 'checkedIn': true, 'paymentStatus': 'paid', 'fee': 5000},
    {'token': 'A-025', 'citizen': 'Saman Perera', 'nic': '855420159V', 'service': 'NIC Card', 'time': '11:00 AM', 'status': 'Not Checked In', 'checkedIn': false, 'paymentStatus': 'pending', 'fee': 500},
    {'token': 'A-026', 'citizen': 'Mala Kumari', 'nic': '925230080V', 'service': 'Driving License', 'time': '11:30 AM', 'status': 'Not Checked In', 'checkedIn': false, 'paymentStatus': 'pending', 'fee': 3000},
    {'token': 'A-027', 'citizen': 'Ruwan Jaya', 'nic': '1987456321', 'service': 'Birth Certificate', 'time': '12:00 PM', 'status': 'Checked In', 'checkedIn': true, 'paymentStatus': 'paid', 'fee': 200},
    {'token': 'A-028', 'citizen': 'Deepani Fernando', 'nic': '1978123456', 'service': 'Police Clearance', 'time': '01:30 PM', 'status': 'Not Checked In', 'checkedIn': false, 'paymentStatus': 'pending', 'fee': 1000},
  ];

  socket_io.Socket? _socket;

  @override
  void initState() {
    super.initState();
    _loadAppointmentsFromApi();
    _loadReceptionStats();
    _loadWalkInsFromApi();
    _socket = socket_io.io(
      'http://localhost:3000',
      socket_io.OptionBuilder().setTransports(['websocket']).disableAutoConnect().build(),
    );
    _socket!.on('appointment_update', (_) => _loadAppointmentsFromApi());
    _socket!.on('queue_update', (_) {
      _loadReceptionStats();
      _loadWalkInsFromApi();
      _loadAppointmentsFromApi();
    });
    _socket!.connect();
  }

  Future<void> _loadReceptionStats() async {
    final stats = await WebApiService.getReceptionStats(_receptionOffice);
    if (!mounted || stats == null) return;
    setState(() {
      activeQueueCount = stats['activeQueue'] as int? ?? activeQueueCount;
      todayArrivals = stats['arrivalsToday'] as int? ?? todayArrivals;
      walkInCount = stats['walkInsToday'] as int? ?? walkInCount;
    });
  }

  /// Walk-ins are queue_entries whose token was generated by [_addWalkIn]
  /// (prefixed 'W-'), as opposed to entries created by an appointment
  /// check-in — both live in the same real queue, this just filters the
  /// office's live queue down to the walk-in subset for display here.
  Future<void> _loadWalkInsFromApi() async {
    final rows = await WebApiService.getQueue(_receptionOffice);
    if (!mounted) return;
    final walkIns = rows.where((r) => (r['token']?.toString() ?? '').startsWith('W-')).toList();
    setState(() {
      walkInQueue = walkIns.map((r) => {
        'name': r['citizen_name'] ?? '',
        'nic': r['citizen_nic'],
        'service': r['service'] ?? '',
        'time': r['wait_time'] ?? '',
        'token': r['token'] ?? '',
        'status': 'Waiting',
      }).toList();
    });
  }

  @override
  void dispose() {
    _socket?.dispose();
    _scrollController.dispose();
    super.dispose();
  }

  /// Replaces the mock `todayAppointments` with real bookings for today
  /// from Postgres, the same source `web_queue_management.dart` already
  /// reads for the live queue. Falls back to the mock list if the backend
  /// is unreachable or nothing's booked for today yet.
  Future<void> _loadAppointmentsFromApi() async {
    final rows = await WebApiService.getAppointments();
    if (!mounted || rows.isEmpty) return;
    final now = DateTime.now();
    final todayStr = '${now.year.toString().padLeft(4, '0')}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')}';
    final todays = rows
        .where((r) => (r['date']?.toString() ?? '').startsWith(todayStr))
        .where((r) => (r['office']?.toString() ?? '') == _receptionOffice)
        .toList();
    if (todays.isEmpty) return;
    setState(() {
      todayAppointments = todays.map((r) => {
        'id': r['id'],
        'token': r['token'] ?? '',
        'citizen': r['citizen_name'] ?? '',
        'nic': r['citizen_nic'],
        'service': r['service'] ?? '',
        'time': r['time'] ?? '',
        'status': 'Not Checked In',
        'checkedIn': false,
        'paymentStatus': r['payment_status'] ?? 'pending',
        'fee': double.tryParse(r['fee_amount']?.toString() ?? '') ?? 0,
      }).toList();
    });
  }

  List<Map<String, dynamic>> walkInQueue = [];

  /// Notifies the citizen identified by [nic] via the `notifications`
  /// collection (the same one the citizen app's Notifications screen reads
  /// live). Looks the uid up through `nic_index`, same as login does.
  Future<void> _notifyCitizenByNic({
    required String? nic,
    required String title,
    required String message,
  }) async {
    if (nic == null || nic.isEmpty) return;
    try {
      final indexDoc = await FirebaseFirestore.instance.collection('nic_index').doc(nic.toUpperCase()).get();
      final uid = indexDoc.data()?['uid'] as String?;
      if (uid == null) return;
      await FirebaseFirestore.instance.collection('notifications').add({
        'uid': uid,
        'title': title,
        'message': message,
        'type': 'appointment',
        'isRead': false,
        'createdAt': FieldValue.serverTimestamp(),
      });
    } catch (e) {
      debugPrint('_notifyCitizenByNic error: $e');
    }
  }

  void _processCheckIn(String qrData) {
    // The QR encodes the appointment details directly as JSON (self-contained
    // — works regardless of what network the citizen's phone is on, unlike a
    // URL to the backend's LAN address). Extract appointmentId from that.
    // Falls back to the URL-path form (an older format this briefly used)
    // and finally a raw token/citizen-substring match for any QR still in an
    // even older format.
    String lookupId = qrData;
    try {
      final decoded = jsonDecode(qrData);
      if (decoded is Map && decoded['appointmentId'] is String) {
        lookupId = decoded['appointmentId'] as String;
      }
    } catch (_) {
      try {
        final uri = Uri.parse(qrData);
        if (uri.pathSegments.isNotEmpty) {
          lookupId = uri.pathSegments.last;
        }
      } catch (_) {}
    }

    final appointment = todayAppointments.firstWhere(
      (apt) => apt['id'] == lookupId || apt['token'] == qrData || apt['citizen'].contains(qrData),
      orElse: () => {},
    );

    if (appointment.isNotEmpty && !appointment['checkedIn']) {
      setState(() {
        appointment['checkedIn'] = true;
        appointment['status'] = 'Checked In';
        scannedData = 'web_checkin_status_scanned'.tr(args: ['${appointment['citizen']}', '${appointment['token']}']);
        _scanResultKind = 'success';
      });

      final paymentStatus = appointment['paymentStatus'] == 'paid' ? 'web_payment_completed'.tr() : 'web_payment_pending_counter'.tr();
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('web_checkin_success_snackbar'.tr(args: ['${appointment['citizen']}', '${appointment['token']}', paymentStatus])),
          backgroundColor: Colors.green,
          behavior: SnackBarBehavior.floating,
          duration: const Duration(seconds: 3),
        ),
      );
      _showScanResultDialog(
        title: 'web_checkin_status_scanned_title'.tr(),
        color: Colors.green,
        icon: Icons.check_circle,
        rows: [
          ('web_col_citizen'.tr(), '${appointment['citizen']}'),
          ('qr_detail_token_label'.tr(), '${appointment['token']}'),
          ('web_col_payment'.tr(), paymentStatus),
        ],
      );
      _notifyCitizenByNic(
        nic: appointment['nic'] as String?,
        title: 'Checked In',
        message: 'You have been checked in for ${appointment['service']}. Token ${appointment['token']} is now active — please wait to be called.',
      );
      WebApiService.addToQueue(
        token: appointment['token'] as String,
        officeId: _receptionOffice,
        citizenName: appointment['citizen'] as String,
        citizenNic: appointment['nic'] as String?,
        service: appointment['service'] as String,
        paymentStatus: appointment['paymentStatus'] as String,
        fee: (appointment['fee'] as num).toDouble(),
        officerName: 'Reception Officer',
      );
    } else if (appointment.isEmpty) {
      setState(() {
        scannedData = 'web_invalid_qr_scanned'.tr();
        _scanResultKind = 'invalid';
      });
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('web_invalid_qr_snackbar'.tr()), backgroundColor: Colors.red),
      );
      _showScanResultDialog(
        title: 'web_invalid_qr_scanned'.tr(),
        color: Colors.red,
        icon: Icons.error,
        rows: const [],
      );
    } else {
      setState(() {
        scannedData = 'web_already_checked_in_scanned'.tr(args: ['${appointment['citizen']}']);
        _scanResultKind = 'already';
      });
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('web_already_checked_in_snackbar'.tr(args: ['${appointment['citizen']}'])), backgroundColor: Colors.orange),
      );
      _showScanResultDialog(
        title: 'web_already_checked_in_scanned'.tr(args: ['${appointment['citizen']}']),
        color: Colors.orange,
        icon: Icons.info,
        rows: [
          ('web_col_citizen'.tr(), '${appointment['citizen']}'),
          ('qr_detail_token_label'.tr(), '${appointment['token']}'),
        ],
      );
    }

    Future.delayed(const Duration(seconds: 2), () {
      if (mounted) {
        setState(() {
          scannedData = '';
          _scanResultKind = '';
        });
      }
    });
  }

  // Shows the scan outcome as a popup (in addition to the existing snackbar
  // and inline scanner-box text) so the officer gets a clear, unmissable
  // confirmation of who was checked in, their token, and payment status.
  void _showScanResultDialog({
    required String title,
    required Color color,
    required IconData icon,
    required List<(String, String)> rows,
  }) {
    showDialog(
      context: context,
      builder: (dialogContext) => AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        title: Row(
          children: [
            Icon(icon, color: color),
            const SizedBox(width: 10),
            Expanded(child: Text(title)),
          ],
        ),
        content: rows.isEmpty
            ? null
            : Column(
                mainAxisSize: MainAxisSize.min,
                children: rows
                    .map((row) => Padding(
                          padding: const EdgeInsets.symmetric(vertical: 4),
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Text(row.$1, style: const TextStyle(color: Colors.grey)),
                              Text(row.$2, style: const TextStyle(fontWeight: FontWeight.w600)),
                            ],
                          ),
                        ))
                    .toList(),
              ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(dialogContext),
            child: Text('ok'.tr()),
          ),
        ],
      ),
    );
  }

  void _addWalkIn() {
    final nameController = TextEditingController();
    final nicController = TextEditingController();
    String selectedService = 'Passport Renewal';

    showDialog(
      context: context,
      builder: (dialogContext) => StatefulBuilder(
        builder: (dialogContext, setDialogState) => AlertDialog(
          title: Text('web_walkin_registration_title'.tr()),
          content: SizedBox(
            width: 400,
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                TextField(
                  controller: nameController,
                  decoration: InputDecoration(
                    labelText: 'web_citizen_name'.tr(),
                    prefixIcon: const Icon(Icons.person),
                  ),
                ),
                const SizedBox(height: 12),
                TextField(
                  controller: nicController,
                  decoration: InputDecoration(
                    labelText: 'web_nic_number'.tr(),
                    prefixIcon: const Icon(Icons.badge),
                  ),
                ),
                const SizedBox(height: 12),
                DropdownButtonFormField<String>(
                  initialValue: selectedService,
                  decoration: InputDecoration(
                    labelText: 'web_service_type'.tr(),
                    prefixIcon: const Icon(Icons.assignment),
                  ),
                  items: const [
                    DropdownMenuItem(value: 'Passport Renewal', child: Text('Passport Renewal')),
                    DropdownMenuItem(value: 'NIC Card', child: Text('NIC Card')),
                    DropdownMenuItem(value: 'Driving License', child: Text('Driving License')),
                    DropdownMenuItem(value: 'Birth Certificate', child: Text('Birth Certificate')),
                  ],
                  onChanged: (value) => setDialogState(() => selectedService = value ?? selectedService),
                ),
              ],
            ),
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(dialogContext),
              child: Text('cancel'.tr()),
            ),
            ElevatedButton(
              onPressed: () async {
                final name = nameController.text.trim();
                if (name.isEmpty) return;
                final nic = nicController.text.trim();
                final token = 'W-${(walkInQueue.length + 1).toString().padLeft(3, '0')}';
                Navigator.pop(dialogContext);
                await WebApiService.addToQueue(
                  token: token,
                  officeId: _receptionOffice,
                  citizenName: name,
                  citizenNic: nic.isNotEmpty ? nic : null,
                  service: selectedService,
                  paymentStatus: 'pending',
                  fee: 0,
                  officerName: 'Reception Officer',
                );
                await _loadWalkInsFromApi();
                await _loadReceptionStats();
                if (!mounted) return;
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(content: Text('web_walkin_registered_success'.tr()), backgroundColor: Colors.green),
                );
              },
              style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFF1A56DB)),
              child: Text('web_register_button'.tr()),
            ),
          ],
        ),
      ),
    );
  }

  Future<void> _callNextWalkIn() async {
    if (walkInQueue.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('web_no_walkins_message'.tr()), backgroundColor: Colors.orange),
      );
      return;
    }
    final next = walkInQueue.first;
    await WebApiService.serveToken(next['token'] as String, 'Reception Officer');
    _notifyCitizenByNic(
      nic: next['nic'] as String?,
      title: 'Your Token is Called',
      message: 'Token ${next['token']} is now being served. Please proceed to the counter.',
    );
    await _loadWalkInsFromApi();
    await _loadReceptionStats();
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text('web_calling_to_counter'.tr(args: ['${next['name']}', '${next['token']}'])),
        backgroundColor: Colors.blue,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('web_reception_dashboard'.tr()),
        backgroundColor: Colors.transparent,
        elevation: 0,
        actions: [
          Container(
            margin: const EdgeInsets.only(right: 20),
            child: Row(
              children: [
                IconButton(
                  padding: EdgeInsets.zero,
                  constraints: const BoxConstraints(),
                  icon: const Icon(Icons.notifications_none, color: Colors.grey),
                  onPressed: () => Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (context) => WebNotifications(userRole: widget.userRole, staffId: widget.staffId),
                    ),
                  ),
                ),
                const SizedBox(width: 16),
                const CircleAvatar(
                  radius: 20,
                  backgroundColor: Color(0xFF1A56DB),
                  child: Icon(Icons.person, color: Colors.white, size: 20),
                ),
                const SizedBox(width: 8),
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Text('web_reception_officer_label'.tr(), style: const TextStyle(fontWeight: FontWeight.w600)),
                    Text('web_checkin_label'.tr(), style: const TextStyle(fontSize: 11, color: Colors.grey)),
                  ],
                ),
              ],
            ),
          ),
        ],
      ),
      body: SingleChildScrollView(
        controller: _scrollController,
        padding: const EdgeInsets.all(24),
        child: Column(
          children: [
            Row(
              children: [
                _buildStatCard('web_active_queue'.tr(), '$activeQueueCount', Icons.queue, Colors.blue,
                    onTap: () => _scrollToSection(_walkInKey)),
                const SizedBox(width: 16),
                _buildStatCard('web_todays_arrivals'.tr(), '$todayArrivals', Icons.people, Colors.green,
                    onTap: () => _scrollToSection(_appointmentsKey)),
                const SizedBox(width: 16),
                _buildStatCard('web_walkins_today'.tr(), '$walkInCount', Icons.person_add, Colors.orange,
                    onTap: () => _scrollToSection(_walkInKey)),
                const SizedBox(width: 16),
                _buildStatCard('web_menu_appointments'.tr(), '${todayAppointments.length}', Icons.calendar_today, Colors.purple,
                    onTap: () => Navigator.push(context, MaterialPageRoute(builder: (context) => WebAppointments(userRole: widget.userRole, staffId: widget.staffId)))),
              ],
            ),
            const SizedBox(height: 24),
            Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Expanded(
                  flex: 2,
                  child: Container(
                    padding: const EdgeInsets.all(20),
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(20),
                      boxShadow: [
                        BoxShadow(color: Colors.grey.withOpacity(0.1), blurRadius: 10),
                      ],
                    ),
                    child: Column(
                      children: [
                        Text(
                          'web_qr_checkin_title'.tr(),
                          style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                        ),
                        const SizedBox(height: 16),
                        Container(
                          height: 280,
                          decoration: BoxDecoration(
                            border: Border.all(color: const Color(0xFF1A56DB), width: 2),
                            borderRadius: BorderRadius.circular(16),
                          ),
                          child: ClipRRect(
                            borderRadius: BorderRadius.circular(14),
                            child: isScanning
                                ? MobileScanner(
                                    onDetect: (capture) {
                                      final barcode = capture.barcodes.first;
                                      if (barcode.rawValue != null) {
                                        setState(() {
                                          isScanning = false;
                                        });
                                        _processCheckIn(barcode.rawValue!);
                                      }
                                    },
                                  )
                                : Center(
                                    child: Column(
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      children: [
                                        Icon(
                                          Icons.qr_code_scanner,
                                          size: 80,
                                          color: Colors.grey.shade300,
                                        ),
                                        const SizedBox(height: 16),
                                        Text(
                                          scannedData.isEmpty
                                              ? 'web_ready_to_scan'.tr()
                                              : scannedData,
                                          style: TextStyle(
                                            color: _scanResultKind == 'success'
                                                ? Colors.green
                                                : (_scanResultKind == 'invalid' ? Colors.red : Colors.grey),
                                          ),
                                          textAlign: TextAlign.center,
                                        ),
                                      ],
                                    ),
                                  ),
                          ),
                        ),
                        const SizedBox(height: 16),
                        SizedBox(
                          width: double.infinity,
                          child: ElevatedButton.icon(
                            onPressed: () {
                              setState(() {
                                isScanning = !isScanning;
                                if (!isScanning) {
                                  scannedData = '';
                                }
                              });
                            },
                            icon: Icon(isScanning ? Icons.stop : Icons.qr_code_scanner),
                            label: Text(isScanning ? 'web_stop_scanning'.tr() : 'web_start_scanning'.tr()),
                            style: ElevatedButton.styleFrom(
                              backgroundColor: isScanning ? Colors.red : const Color(0xFF1A56DB),
                              padding: const EdgeInsets.symmetric(vertical: 14),
                            ),
                          ),
                        ),
                        const SizedBox(height: 12),
                        Container(
                          padding: const EdgeInsets.all(12),
                          decoration: BoxDecoration(
                            color: Colors.blue.withOpacity(0.05),
                            borderRadius: BorderRadius.circular(12),
                          ),
                          child: Row(
                            children: [
                              const Icon(Icons.info_outline, size: 16, color: Colors.blue),
                              const SizedBox(width: 8),
                              Expanded(
                                child: Text(
                                  'web_scan_qr_hint'.tr(),
                                  style: const TextStyle(fontSize: 12),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                const SizedBox(width: 24),
                Expanded(
                  flex: 3,
                  child: Column(
                    children: [
                      Container(
                        key: _appointmentsKey,
                        padding: const EdgeInsets.all(20),
                        decoration: BoxDecoration(
                          color: Colors.white,
                          borderRadius: BorderRadius.circular(20),
                          boxShadow: [
                            BoxShadow(color: Colors.grey.withOpacity(0.1), blurRadius: 10),
                          ],
                        ),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [
                                Text(
                                  'web_stat_todays_appointments'.tr(),
                                  style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                                ),
                                Text(
                                  'web_checked_in_count'.tr(args: ['${todayAppointments.where((a) => a['checkedIn']).length}', '${todayAppointments.length}']),
                                  style: const TextStyle(fontSize: 12, color: Colors.grey),
                                ),
                              ],
                            ),
                            const SizedBox(height: 16),
                            SizedBox(
                              height: 250,
                              child: SingleChildScrollView(
                                scrollDirection: Axis.horizontal,
                                child: DataTable(
                                  columnSpacing: 30,
                                  columns: [
                                    DataColumn(label: Text('web_col_token'.tr())),
                                    DataColumn(label: Text('web_col_citizen'.tr())),
                                    DataColumn(label: Text('web_col_service'.tr())),
                                    DataColumn(label: Text('web_col_time'.tr())),
                                    DataColumn(label: Text('web_fee_label'.tr())),
                                    DataColumn(label: Text('web_col_payment'.tr())),
                                    DataColumn(label: Text('web_col_status'.tr())),
                                    DataColumn(label: Text('web_col_action'.tr())),
                                  ],
                                  rows: todayAppointments.map((apt) {
                                    final isCheckedIn = apt['checkedIn'];
                                    final paymentColor = apt['paymentStatus'] == 'paid' ? Colors.green : Colors.orange;
                                    return DataRow(cells: [
                                      DataCell(Text(apt['token'], style: const TextStyle(fontWeight: FontWeight.bold))),
                                      DataCell(Text(apt['citizen'])),
                                      DataCell(Text(apt['service'])),
                                      DataCell(Text(apt['time'])),
                                      DataCell(Text('Rs. ${apt['fee']}')),
                                      DataCell(Container(
                                        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                                        decoration: BoxDecoration(
                                          color: paymentColor.withOpacity(0.1),
                                          borderRadius: BorderRadius.circular(12),
                                        ),
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          children: [
                                            Icon(
                                              apt['paymentStatus'] == 'paid' ? Icons.check_circle : Icons.pending,
                                              size: 12,
                                              color: paymentColor,
                                            ),
                                            const SizedBox(width: 4),
                                            Text(
                                              apt['paymentStatus'] == 'paid' ? 'web_paid'.tr() : 'pending'.tr(),
                                              style: TextStyle(color: paymentColor, fontSize: 11),
                                            ),
                                          ],
                                        ),
                                      )),
                                      DataCell(Container(
                                        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                                        decoration: BoxDecoration(
                                          color: (isCheckedIn ? Colors.green : Colors.orange).withOpacity(0.1),
                                          borderRadius: BorderRadius.circular(12),
                                        ),
                                        child: Text(
                                          isCheckedIn ? 'web_checked_in_status'.tr() : 'web_not_checked_in_status'.tr(),
                                          style: TextStyle(color: isCheckedIn ? Colors.green : Colors.orange),
                                        ),
                                      )),
                                      DataCell(
                                        isCheckedIn
                                            ? const Icon(Icons.check_circle, color: Colors.green)
                                            : ElevatedButton(
                                                onPressed: () {
                                                  if (apt['paymentStatus'] == 'pending') {
                                                    showDialog(
                                                      context: context,
                                                      builder: (context) => AlertDialog(
                                                        title: Text('web_payment_required'.tr()),
                                                        content: Text('web_payment_pending_counter_message'.tr(args: ['${apt['fee']}'])),
                                                        actions: [
                                                          TextButton(
                                                            onPressed: () => Navigator.pop(context),
                                                            child: Text('ok'.tr()),
                                                          ),
                                                        ],
                                                      ),
                                                    );
                                                  } else {
                                                    setState(() {
                                                      apt['checkedIn'] = true;
                                                      apt['status'] = 'Checked In';
                                                    });
                                                    ScaffoldMessenger.of(context).showSnackBar(
                                                      SnackBar(
                                                        content: Text('web_checked_in_manually_message'.tr(args: ['${apt['citizen']}'])),
                                                        backgroundColor: Colors.green,
                                                      ),
                                                    );
                                                    _notifyCitizenByNic(
                                                      nic: apt['nic'] as String?,
                                                      title: 'Checked In',
                                                      message: 'You have been checked in for ${apt['service']}. Token ${apt['token']} is now active — please wait to be called.',
                                                    );
                                                    WebApiService.addToQueue(
                                                      token: apt['token'] as String,
                                                      officeId: _receptionOffice,
                                                      citizenName: apt['citizen'] as String,
                                                      citizenNic: apt['nic'] as String?,
                                                      service: apt['service'] as String,
                                                      paymentStatus: apt['paymentStatus'] as String,
                                                      fee: (apt['fee'] as num).toDouble(),
                                                      officerName: 'Reception Officer',
                                                    );
                                                  }
                                                },
                                                style: ElevatedButton.styleFrom(
                                                  backgroundColor: apt['paymentStatus'] == 'pending' ? Colors.orange : const Color(0xFF1A56DB),
                                                ),
                                                child: Text(apt['paymentStatus'] == 'pending' ? 'web_collect_payment'.tr() : 'web_check_in_button'.tr()),
                                              ),
                                      ),
                                    ]);
                                  }).toList(),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 20),
                      Container(
                        key: _walkInKey,
                        padding: const EdgeInsets.all(20),
                        decoration: BoxDecoration(
                          color: Colors.white,
                          borderRadius: BorderRadius.circular(20),
                          boxShadow: [
                            BoxShadow(color: Colors.grey.withOpacity(0.1), blurRadius: 10),
                          ],
                        ),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [
                                Text(
                                  'web_walkin_queue_title'.tr(),
                                  style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                                ),
                                Row(
                                  children: [
                                    ElevatedButton.icon(
                                      onPressed: _addWalkIn,
                                      icon: const Icon(Icons.add),
                                      label: Text('web_add_walkin_button'.tr()),
                                      style: ElevatedButton.styleFrom(
                                        backgroundColor: const Color(0xFF10B981),
                                      ),
                                    ),
                                    const SizedBox(width: 12),
                                    ElevatedButton.icon(
                                      onPressed: _callNextWalkIn,
                                      icon: const Icon(Icons.play_arrow),
                                      label: Text('web_call_next'.tr()),
                                      style: ElevatedButton.styleFrom(
                                        backgroundColor: const Color(0xFF1A56DB),
                                      ),
                                    ),
                                  ],
                                ),
                              ],
                            ),
                            const SizedBox(height: 16),
                            walkInQueue.isEmpty
                                ? Padding(
                                    padding: const EdgeInsets.all(40),
                                    child: Center(
                                      child: Text('web_no_walkins_message'.tr()),
                                    ),
                                  )
                                : ListView.builder(
                                    shrinkWrap: true,
                                    physics: const NeverScrollableScrollPhysics(),
                                    itemCount: walkInQueue.length,
                                    itemBuilder: (context, index) {
                                      final walkIn = walkInQueue[index];
                                      return Container(
                                        margin: const EdgeInsets.only(bottom: 8),
                                        padding: const EdgeInsets.all(12),
                                        decoration: BoxDecoration(
                                          color: Colors.grey.shade50,
                                          borderRadius: BorderRadius.circular(12),
                                        ),
                                        child: Row(
                                          children: [
                                            Container(
                                              width: 40,
                                              height: 40,
                                              decoration: BoxDecoration(
                                                color: const Color(0xFF1A56DB).withOpacity(0.1),
                                                borderRadius: BorderRadius.circular(10),
                                              ),
                                              child: Center(
                                                child: Text(
                                                  walkIn['token'],
                                                  style: const TextStyle(
                                                    fontWeight: FontWeight.bold,
                                                    color: Color(0xFF1A56DB),
                                                  ),
                                                ),
                                              ),
                                            ),
                                            const SizedBox(width: 12),
                                            Expanded(
                                              child: Column(
                                                crossAxisAlignment: CrossAxisAlignment.start,
                                                children: [
                                                  Text(walkIn['name'], style: const TextStyle(fontWeight: FontWeight.bold)),
                                                  Text('${walkIn['service']} • ${walkIn['time']}', style: const TextStyle(fontSize: 12, color: Colors.grey)),
                                                ],
                                              ),
                                            ),
                                            Container(
                                              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                                              decoration: BoxDecoration(
                                                color: Colors.orange.withOpacity(0.1),
                                                borderRadius: BorderRadius.circular(12),
                                              ),
                                              child: Text(
                                                'web_waiting_status'.tr(),
                                                style: const TextStyle(color: Colors.orange),
                                              ),
                                            ),
                                          ],
                                        ),
                                      );
                                    },
                                  ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildStatCard(String title, String value, IconData icon, Color color, {VoidCallback? onTap}) {
    final card = Container(
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(16),
          boxShadow: [
            BoxShadow(color: Colors.grey.withOpacity(0.1), blurRadius: 10),
          ],
        ),
        child: Row(
          children: [
            Container(
              padding: const EdgeInsets.all(8),
              decoration: BoxDecoration(color: color.withOpacity(0.1), borderRadius: BorderRadius.circular(12)),
              child: Icon(icon, color: color, size: 24),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(title, style: TextStyle(fontSize: 12, color: Colors.grey.shade600)),
                  Text(value, style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold, color: color)),
                ],
              ),
            ),
          ],
        ),
      );
    return Expanded(
      child: onTap == null
          ? card
          : InkWell(
              onTap: onTap,
              borderRadius: BorderRadius.circular(16),
              mouseCursor: SystemMouseCursors.click,
              child: card,
            ),
    );
  }
}